# Linear Algebra, Gradients, Optimization

## Scalar
Data must be arranged in n-dimensional arrays known as tensor. There are different types of tensor.
**Scalar** single numbers, so it's dimension is 0. In python, we use the numpy package for handle scalar,
 vectors and tensor. Let's create Scalar.

In [4]:
import numpy as np

x = np.array(8)
print(f"x = {x}")
print(type(x))
print(f"dimension: {x.ndim}")

x = 8
<class 'numpy.ndarray'>
dimension: 0


# Vector
Vectors are single dimension array. They may contain large number of elements.

In [5]:
x = np.array([1, 2, 3])
print(f"x = {x}")
print(type(x))
print(f"dimension: {x.ndim}")

x = [1 2 3]
<class 'numpy.ndarray'>
dimension: 1


# Matrics
A matrics are two-dimensional array. We create a random array below.

In [7]:
x = np.zeros((2, 3))
print(f"x = {x}")
print(type(x))
print(f"dimension: {x.ndim}")

x = [[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
dimension: 2


# Tensors
An array that is of dimension **three or greater** is denoted as a "tensor".
Though, vectors and matrics are also special classes of tensors.

In [8]:
tensor = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"tensor = {tensor}")
print(tensor.shape)

tensor = [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
x = np.random.random((2,3,2,4))
x

array([[[[0.44344904, 0.57047511, 0.05602772, 0.36074661],
         [0.24956877, 0.89550552, 0.70174723, 0.44436976]],

        [[0.57678527, 0.07311452, 0.93281642, 0.5395309 ],
         [0.49905488, 0.80606908, 0.8663641 , 0.92569912]],

        [[0.86861264, 0.64746574, 0.28977366, 0.38693207],
         [0.47402136, 0.39183623, 0.09145064, 0.82631506]]],


       [[[0.60160396, 0.96058521, 0.06821449, 0.39306229],
         [0.50045556, 0.24407206, 0.3303789 , 0.58260104]],

        [[0.33184714, 0.10973048, 0.09059198, 0.0837623 ],
         [0.4588253 , 0.99710091, 0.84581592, 0.59204354]],

        [[0.22138326, 0.48473373, 0.15006586, 0.31913841],
         [0.14817486, 0.84784188, 0.02580977, 0.5566538 ]]]])

# Dot Product
Two vectors is the element wise multiplication of the vector, then a sum of the products

In [11]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 5, 6, 7])
print(x * y)
print(x.dot(y))

[ 4 10 18 28]
60


# Norm Of A Vector: